# Generated by Django 4.2.6 on 2023-10-10 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='Task User ID')),
                ('tkt_num', models.CharField(max_length=10, verbose_name='Ticket Number')),
                ('task_num', models.IntegerField(default=0, verbose_name='Task Number')),
                ('title', models.CharField(max_length=50, verbose_name='Task Title')),
                ('description', models.CharField(max_length=255, verbose_name='Task Desciption')),
                ('status', models.CharField(max_length=10, verbose_name='Task Status')),
                ('priority', models.IntegerField(default=0, verbose_name='Task Priority')),
                ('precedence', models.IntegerField(default=0, verbose_name='Task Prcedence')),
                ('requestor', models.CharField(max_length=50, verbose_name='Task Requestor')),
                ('plant', models.CharField(max_length=10, verbose_name='Task Plant')),
                ('assigned_to', models.CharField(max_length=20, verbose_name='Task Assigned To')),
                ('create_date', models.DateTimeField(verbose_name='Task Create Date')),
                ('goal_date', models.DateTimeField(verbose_name='Task Goal Date')),
                ('complete_date', models.DateTimeField(verbose_name='Task Complete Date')),
                ('branch', models.CharField(max_length=40, verbose_name='Task Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='Ticket User ID')),
                ('tkt_num', models.CharField(max_length=10, verbose_name='Ticket Number')),
                ('title', models.CharField(max_length=50, verbose_name='Ticket Title')),
                ('description', models.CharField(max_length=255, verbose_name='Ticket Desciption')),
                ('status', models.CharField(max_length=10, verbose_name='Ticket Status')),
                ('priority', models.IntegerField(default=0, verbose_name='Ticket Priority')),
                ('precedence', models.IntegerField(default=0, verbose_name='Ticket Prcedence')),
                ('requestor', models.CharField(max_length=50, verbose_name='Ticket Requestor')),
                ('plant', models.CharField(max_length=10, verbose_name='Ticket Plant')),
                ('assigned_to', models.CharField(max_length=20, verbose_name='Ticket Assigned To')),
                ('create_date', models.DateTimeField(verbose_name='Ticket Create Date')),
                ('goal_date', models.DateTimeField(verbose_name='Ticket Goal Date')),
                ('complete_date', models.DateTimeField(verbose_name='Ticket Complete Date')),
                ('branch', models.CharField(max_length=40, verbose_name='Ticket Branch')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='Unique User ID')),
                ('user_name', models.CharField(max_length=40, verbose_name='User Name')),
                ('user_lvl', models.IntegerField(default=0, verbose_name='User Level')),
                ('user_status', models.CharField(max_length=10, verbose_name='User Status')),
                ('last_login', models.DateTimeField(verbose_name='Last Login')),
                ('bad_logins', models.IntegerField(default=0, verbose_name='Bad Logins')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tkt_num', models.CharField(max_length=10, verbose_name='Ticket Number')),
                ('task_num', models.IntegerField(default=0, verbose_name='Task Number')),
                ('note', models.CharField(max_length=255, verbose_name='Note')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.user')),
            ],
        ),
    ]
