# Generated by Django 4.2.6 on 2023-10-10 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='task_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.task'),
        ),
        migrations.AlterField(
            model_name='note',
            name='tkt_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.ticket'),
        ),
        migrations.AlterField(
            model_name='task',
            name='tkt_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.ticket'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.user'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.user'),
        ),
    ]
