# Generated by Django 4.2.6 on 2023-10-11 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_note_task_num_alter_note_tkt_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=20, unique=True, verbose_name='Unique User ID'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(fields=('user_id', 'tkt_num', 'task_num'), name='client_task_unique'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(fields=('user_id', 'tkt_num'), name='client_ticket_unique'),
        ),
    ]
