# Generated by Django 4.2.6 on 2023-10-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_user_user_id_task_client_task_unique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Task Complete Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Task Create Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='goal_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Task Goal Date'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ticket Complete Date'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ticket Create Date'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='goal_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ticket Goal Date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Login'),
        ),
    ]
